export type BenchmarkBand = {
  low: string;
  mid: string;
  high: string;
};

export type ProgrammaticPage = {
  slug: string;
  name: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  primaryKeyword: string;
  relatedKeywords: string[];
  benchmark: BenchmarkBand;
  notes: string[];
  recommendedCalculatorPath: string;
};

export const industryPages: ProgrammaticPage[] = [
  {
    slug: "shopify",
    name: "Shopify eCommerce",
    title: "Shopify ROAS Calculator by Industry",
    description: "Calculate ROAS and break-even targets for Shopify stores with practical profitability benchmarks.",
    h1: "Shopify ROAS Calculator and Benchmarks",
    intro: "Estimate return on ad spend for Shopify growth campaigns and map outcomes to margin-based break-even targets.",
    primaryKeyword: "shopify roas calculator",
    relatedKeywords: ["ecommerce roas benchmark", "shopify break-even roas", "meta dtc roas"],
    benchmark: { low: "1.8x", mid: "3.2x", high: "5.0x+" },
    notes: ["Account for COGS, shipping, and refunds.", "Compare channel ROAS to blended MER before scaling."],
    recommendedCalculatorPath: "/roas/meta-dtc-roas",
  },
  {
    slug: "saas",
    name: "SaaS",
    title: "SaaS ROAS Calculator with CAC Payback Context",
    description: "Model SaaS ROAS with CAC payback and LTV context to avoid unprofitable paid growth.",
    h1: "SaaS ROAS Calculator and Payback Benchmarks",
    intro: "Translate campaign efficiency into SaaS unit economics by linking ROAS to CAC, LTV, and cash flow recovery speed.",
    primaryKeyword: "saas roas calculator",
    relatedKeywords: ["saas cac payback", "ltv cac ratio", "b2b saas roas"],
    benchmark: { low: "1.5x", mid: "2.8x", high: "4.0x+" },
    notes: ["Track payback period monthly.", "Use pipeline quality, not only lead volume, for decisions."],
    recommendedCalculatorPath: "/payback-period-calculator",
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    title: "Real Estate ROAS Calculator (Lead-to-Deal)",
    description: "Estimate ROAS for real estate campaigns using CPL, close rates, and commission assumptions.",
    h1: "Real Estate ROAS Calculator",
    intro: "Map lead generation spend to closed deal value so media decisions match actual commission outcomes.",
    primaryKeyword: "real estate roas calculator",
    relatedKeywords: ["real estate lead generation roi", "cpl to roas", "agent ads profitability"],
    benchmark: { low: "1.2x", mid: "2.2x", high: "3.5x+" },
    notes: ["Use realistic close-rate assumptions.", "Segment benchmarks by buyer vs seller leads."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "legal-services",
    name: "Legal Services",
    title: "Law Firm ROAS Calculator for Paid Leads",
    description: "Calculate law firm ad ROAS based on qualified lead rates and average case value.",
    h1: "Law Firm ROAS Calculator",
    intro: "Estimate profitability for legal paid media by linking lead quality and case economics to ROAS.",
    primaryKeyword: "law firm roas calculator",
    relatedKeywords: ["legal ads roi", "law firm cpl benchmark", "google ads for lawyers roas"],
    benchmark: { low: "1.3x", mid: "2.5x", high: "4.0x+" },
    notes: ["Track signed-client conversion.", "Exclude unqualified consult volume from success metrics."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "dentist",
    name: "Dental Clinics",
    title: "Dental Clinic ROAS Calculator",
    description: "Model dental ad ROAS using appointment show rates, treatment value, and CAC thresholds.",
    h1: "Dental Clinic ROAS Calculator",
    intro: "Connect paid search and social lead costs to booked appointments and treatment revenue.",
    primaryKeyword: "dental roas calculator",
    relatedKeywords: ["dentist ads roi", "clinic cpa benchmark", "healthcare lead gen roas"],
    benchmark: { low: "1.4x", mid: "2.6x", high: "4.2x+" },
    notes: ["Measure show rate separately from booked leads.", "Track high-value treatments independently."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "edtech",
    name: "EdTech",
    title: "EdTech ROAS Calculator for Course and Subscription Growth",
    description: "Calculate EdTech ROAS by modeling trial-to-paid conversion and retention assumptions.",
    h1: "EdTech ROAS Calculator",
    intro: "Evaluate paid growth efficiency for courses and recurring products with conversion and retention context.",
    primaryKeyword: "edtech roas calculator",
    relatedKeywords: ["course ads roas", "subscription ltv cac", "education lead generation roi"],
    benchmark: { low: "1.6x", mid: "2.9x", high: "4.5x+" },
    notes: ["Model refunds and churn.", "Split benchmark by one-time courses vs subscriptions."],
    recommendedCalculatorPath: "/ltv-calculator",
  },
  {
    slug: "automotive",
    name: "Automotive",
    title: "Automotive ROAS Calculator for Dealer Campaigns",
    description: "Estimate dealer campaign ROAS based on lead quality, showroom conversion, and average deal value.",
    h1: "Automotive ROAS Calculator",
    intro: "Translate ad spend into measurable dealership outcomes across lead forms, calls, and booked visits.",
    primaryKeyword: "automotive roas calculator",
    relatedKeywords: ["dealer ads roi", "auto lead benchmark", "cpl to sales conversion"],
    benchmark: { low: "1.1x", mid: "2.1x", high: "3.4x+" },
    notes: ["Track offline attribution where possible.", "Separate new vs used vehicle economics."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "travel",
    name: "Travel",
    title: "Travel ROAS Calculator for Booking Campaigns",
    description: "Calculate travel campaign ROAS using booking value, cancellation rates, and margin assumptions.",
    h1: "Travel ROAS Calculator",
    intro: "Model paid media efficiency for travel demand while accounting for cancellations and seasonal swings.",
    primaryKeyword: "travel roas calculator",
    relatedKeywords: ["hotel ads roas", "travel booking roi", "tourism ppc benchmark"],
    benchmark: { low: "1.7x", mid: "3.0x", high: "4.8x+" },
    notes: ["Adjust for cancellation rates.", "Benchmark by season and destination demand."],
    recommendedCalculatorPath: "/roas/google-ads",
  },
  {
    slug: "b2b-services",
    name: "B2B Services",
    title: "B2B Services ROAS Calculator",
    description: "Estimate B2B paid acquisition ROAS with pipeline conversion and deal cycle assumptions.",
    h1: "B2B Services ROAS Calculator",
    intro: "Link paid lead costs to pipeline outcomes and closed revenue for accurate B2B ROAS decisions.",
    primaryKeyword: "b2b roas calculator",
    relatedKeywords: ["b2b cpl to roas", "pipeline roi", "service business ad profitability"],
    benchmark: { low: "1.2x", mid: "2.3x", high: "3.8x+" },
    notes: ["Model sales cycle lag in reporting.", "Use pipeline quality score in weekly review."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "mobile-apps",
    name: "Mobile Apps",
    title: "Mobile App ROAS Calculator (UA and Subscription)",
    description: "Calculate app marketing ROAS by connecting install cost, in-app revenue, and retention.",
    h1: "Mobile App ROAS Calculator",
    intro: "Estimate user acquisition efficiency for app growth using in-app monetization and retention assumptions.",
    primaryKeyword: "app roas calculator",
    relatedKeywords: ["mobile app marketing roi", "ua roas benchmark", "subscription app ltv"],
    benchmark: { low: "1.3x", mid: "2.4x", high: "3.9x+" },
    notes: ["Monitor cohort-based LTV.", "Separate paid and organic contribution in blended models."],
    recommendedCalculatorPath: "/ltv-calculator",
  },
];

export const platformPages: ProgrammaticPage[] = [
  {
    slug: "google-ads",
    name: "Google Ads",
    title: "Google Ads ROAS Calculator by Platform",
    description: "Calculate Google Ads ROAS and break-even targets for Search, Shopping, and Performance Max campaigns.",
    h1: "Google Ads ROAS Calculator",
    intro: "Evaluate return on ad spend for Google campaigns and compare performance against margin-based thresholds.",
    primaryKeyword: "google ads roas calculator",
    relatedKeywords: ["search ads roas", "shopping ads benchmark", "pmax profitability"],
    benchmark: { low: "1.9x", mid: "3.3x", high: "5.2x+" },
    notes: ["Separate branded and non-branded traffic.", "Validate feed quality impact for Shopping."],
    recommendedCalculatorPath: "/roas/google-ads",
  },
  {
    slug: "facebook-ads",
    name: "Facebook Ads",
    title: "Facebook Ads ROAS Calculator by Platform",
    description: "Model Facebook and Instagram ad ROAS with break-even and creative testing context.",
    h1: "Facebook Ads ROAS Calculator",
    intro: "Use platform-specific assumptions for audience quality, creative fatigue, and conversion lag.",
    primaryKeyword: "facebook ads roas calculator",
    relatedKeywords: ["meta ads roas benchmark", "instagram ads roas", "dtc paid social roas"],
    benchmark: { low: "1.8x", mid: "3.1x", high: "5.0x+" },
    notes: ["Refresh creative regularly.", "Compare prospecting and retargeting efficiency separately."],
    recommendedCalculatorPath: "/roas/facebook-ads",
  },
  {
    slug: "tiktok-ads",
    name: "TikTok Ads",
    title: "TikTok Ads ROAS Calculator by Platform",
    description: "Estimate TikTok ROAS with creative-led testing and conversion quality assumptions.",
    h1: "TikTok Ads ROAS Calculator",
    intro: "Evaluate TikTok campaign outcomes where creative velocity and post-click funnel quality drive ROAS variance.",
    primaryKeyword: "tiktok roas calculator",
    relatedKeywords: ["spark ads roi", "tiktok ecommerce roas", "paid social benchmark"],
    benchmark: { low: "1.6x", mid: "2.8x", high: "4.4x+" },
    notes: ["Use high test velocity for creative.", "Track conversion quality, not only click volume."],
    recommendedCalculatorPath: "/roas/tiktok-ads",
  },
  {
    slug: "linkedin-ads",
    name: "LinkedIn Ads",
    title: "LinkedIn Ads ROAS Calculator for B2B",
    description: "Calculate LinkedIn ROAS using CPL, lead quality, and pipeline conversion assumptions.",
    h1: "LinkedIn Ads ROAS Calculator",
    intro: "Model B2B paid social economics by tying lead cost to sales-qualified pipeline and close rates.",
    primaryKeyword: "linkedin ads roas calculator",
    relatedKeywords: ["linkedin lead gen roi", "b2b cpl benchmark", "pipeline roas"],
    benchmark: { low: "1.1x", mid: "2.0x", high: "3.5x+" },
    notes: ["Track MQL to SQL conversion.", "Use longer attribution windows for B2B deals."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "youtube-ads",
    name: "YouTube Ads",
    title: "YouTube Ads ROAS Calculator",
    description: "Estimate YouTube ad ROAS with assisted conversion and blended efficiency context.",
    h1: "YouTube Ads ROAS Calculator",
    intro: "Evaluate video campaign performance with both direct and assisted conversion contributions.",
    primaryKeyword: "youtube ads roas calculator",
    relatedKeywords: ["video ads roi", "youtube performance benchmark", "upper funnel roas"],
    benchmark: { low: "1.3x", mid: "2.4x", high: "4.0x+" },
    notes: ["Measure post-view behavior where possible.", "Compare with blended MER for executive reporting."],
    recommendedCalculatorPath: "/mer-calculator",
  },
  {
    slug: "amazon-ppc",
    name: "Amazon PPC",
    title: "Amazon PPC ROAS and ACoS Calculator",
    description: "Convert ACoS to ROAS and model Amazon Sponsored Products profitability.",
    h1: "Amazon PPC ROAS Calculator",
    intro: "Estimate Amazon ad efficiency with ACoS/ROAS conversion and margin-aware decision support.",
    primaryKeyword: "amazon ppc roas calculator",
    relatedKeywords: ["acos to roas", "amazon ads benchmark", "fba ad profitability"],
    benchmark: { low: "2.0x", mid: "3.4x", high: "5.5x+" },
    notes: ["Track TACoS alongside ACoS.", "Separate branded and generic keyword portfolios."],
    recommendedCalculatorPath: "/roas/amazon-ppc-acos",
  },
  {
    slug: "pinterest-ads",
    name: "Pinterest Ads",
    title: "Pinterest Ads ROAS Calculator",
    description: "Calculate Pinterest ads ROAS for visual commerce and feed-driven campaigns.",
    h1: "Pinterest Ads ROAS Calculator",
    intro: "Model Pinterest campaign efficiency for catalog and inspiration-led purchase journeys.",
    primaryKeyword: "pinterest roas calculator",
    relatedKeywords: ["pinterest shopping ads roi", "visual commerce benchmark", "social commerce roas"],
    benchmark: { low: "1.7x", mid: "2.9x", high: "4.6x+" },
    notes: ["Use seasonal benchmarks for planning.", "Optimize product feed quality for intent matching."],
    recommendedCalculatorPath: "/roas/pinterest-ads",
  },
];

export const scenarioPages: ProgrammaticPage[] = [
  {
    slug: "break-even-roas-by-margin",
    name: "Break-Even ROAS by Margin",
    title: "Break-Even ROAS by Margin Scenario",
    description: "Find break-even ROAS targets by margin band and use them as campaign guardrails.",
    h1: "Break-Even ROAS by Margin",
    intro: "Set realistic ROAS thresholds with margin-based math before making budget decisions.",
    primaryKeyword: "break even roas by margin",
    relatedKeywords: ["break-even roas formula", "margin calculator", "profitability threshold"],
    benchmark: { low: "2.0x", mid: "3.3x", high: "5.0x+" },
    notes: ["Lower margin requires higher ROAS.", "Recalculate thresholds after pricing changes."],
    recommendedCalculatorPath: "/break-even-roas-by-margin",
  },
  {
    slug: "target-roas-by-aov",
    name: "Target ROAS by AOV",
    title: "Target ROAS by AOV Scenario Calculator",
    description: "Estimate target ROAS by average order value and margin assumptions.",
    h1: "Target ROAS by AOV Scenario",
    intro: "Use AOV and margin sensitivity to define channel-level ROAS targets for planning.",
    primaryKeyword: "target roas by aov",
    relatedKeywords: ["aov roas calculator", "ecommerce target roas", "ad budget planning"],
    benchmark: { low: "2.2x", mid: "3.4x", high: "5.2x+" },
    notes: ["Model discounts and promo periods separately.", "Use conservative AOV for scaling plans."],
    recommendedCalculatorPath: "/roas/target-cpa",
  },
  {
    slug: "lead-gen-cpl-to-roas",
    name: "Lead Gen CPL to ROAS",
    title: "Lead Generation CPL to ROAS Scenario",
    description: "Convert CPL and close-rate assumptions into ROAS projections for lead generation campaigns.",
    h1: "Lead Gen CPL to ROAS Scenario",
    intro: "Map lead economics to revenue outcomes so paid lead budgets stay tied to pipeline quality.",
    primaryKeyword: "cpl to roas calculator",
    relatedKeywords: ["lead generation roas", "close rate calculator", "b2b paid media roi"],
    benchmark: { low: "1.2x", mid: "2.4x", high: "4.0x+" },
    notes: ["Track qualified lead rate.", "Review close-rate assumptions monthly."],
    recommendedCalculatorPath: "/roas/lead-gen-cpl-roas",
  },
  {
    slug: "subscription-roas-with-ltv",
    name: "Subscription ROAS with LTV",
    title: "Subscription ROAS with LTV Scenario",
    description: "Model subscription ad profitability with retention-driven LTV and CAC payback context.",
    h1: "Subscription ROAS with LTV Scenario",
    intro: "Estimate whether paid growth is sustainable by combining near-term ROAS with longer-term LTV recovery.",
    primaryKeyword: "subscription roas calculator",
    relatedKeywords: ["ltv cac payback", "saas subscription roi", "retention based roas"],
    benchmark: { low: "1.4x", mid: "2.6x", high: "4.2x+" },
    notes: ["Use cohort-level retention data.", "Monitor payback monthly to manage cash flow risk."],
    recommendedCalculatorPath: "/ltv-calculator",
  },
  {
    slug: "agency-client-roas-reporting",
    name: "Agency Client ROAS Reporting",
    title: "Agency Client ROAS Reporting Scenario",
    description: "Standardize agency ROAS reporting with benchmark context, break-even targets, and action rules.",
    h1: "Agency Client ROAS Reporting Scenario",
    intro: "Build consistent reporting narratives by connecting channel ROAS, blended MER, and next-step decision logic.",
    primaryKeyword: "agency roas reporting template",
    relatedKeywords: ["client roas dashboard", "ppc reporting framework", "media efficiency reporting"],
    benchmark: { low: "1.8x", mid: "3.0x", high: "4.8x+" },
    notes: ["Separate channel and blended reporting.", "Include action thresholds in every report."],
    recommendedCalculatorPath: "/resources/roas-planning-template",
  },
];

export function getIndustryBySlug(slug: string): ProgrammaticPage | undefined {
  return industryPages.find((item) => item.slug === slug);
}

export function getPlatformBySlug(slug: string): ProgrammaticPage | undefined {
  return platformPages.find((item) => item.slug === slug);
}

export function getScenarioBySlug(slug: string): ProgrammaticPage | undefined {
  return scenarioPages.find((item) => item.slug === slug);
}
