import Link from "next/link";
import type { Metadata } from "next";
import PaybackCalculatorClient from "./PaybackCalculatorClient";
import EmailCaptureCard from "@/app/components/EmailCaptureCard";

export const metadata: Metadata = {
  title: "CAC Payback Period Calculator",
  description:
    "Estimate CAC payback period in months using CAC, gross margin, and monthly revenue per customer.",
  keywords: ["payback period calculator", "cac payback", "saas payback period", "ltv cac payback"],
  alternates: {
    canonical: "https://roas-calculator.tech/payback-period-calculator",
  },
  openGraph: {
    title: "CAC Payback Period Calculator",
    description: "Calculate how many months it takes to recover customer acquisition cost.",
    url: "https://roas-calculator.tech/payback-period-calculator",
  },
  twitter: {
    card: "summary_large_image",
    title: "CAC Payback Period Calculator",
    description: "Calculate how many months it takes to recover customer acquisition cost.",
  },
};

export default function PaybackPeriodPage() {
  const webAppData = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "CAC Payback Period Calculator",
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    url: "https://roas-calculator.tech/payback-period-calculator",
  };
  const howToData = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to calculate CAC payback period",
    step: [
      { "@type": "HowToStep", name: "Enter CAC", text: "Use current acquisition cost per customer from paid channels." },
      { "@type": "HowToStep", name: "Enter monthly revenue and margin", text: "Add realistic revenue per customer and gross margin assumptions." },
      { "@type": "HowToStep", name: "Review payback months", text: "Use payback months to decide scale, hold, or budget reduction." },
    ],
  };
  const faqData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is CAC payback period?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "CAC payback period is the time required to recover customer acquisition cost from gross profit generated by that customer.",
        },
      },
      {
        "@type": "Question",
        name: "What payback period is healthy for SaaS?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Many SaaS teams target under 12 months, but acceptable ranges depend on cash flow, retention quality, and growth strategy.",
        },
      },
    ],
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 py-12 px-4 md:px-6">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppData) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToData) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqData) }} />
      <main className="max-w-4xl mx-auto bg-white border border-slate-200 rounded-2xl shadow-sm p-8 md:p-12 space-y-8">
        <div>
          <Link href="/ppc-toolkit" className="text-sm text-slate-500 hover:text-blue-600 transition">Back to PPC Toolkit</Link>
          <h1 className="text-3xl md:text-4xl font-bold mt-2">CAC Payback Period Calculator</h1>
          <p className="text-slate-600 mt-3">
            Payback period tells you how quickly acquisition spend returns. This is critical for cash flow and scaling decisions.
          </p>
          <p className="text-slate-700 mt-3">
            Quick answer: payback period is the number of months required to recover CAC from gross profit.
          </p>
        </div>

        <section className="bg-slate-50 border border-slate-200 rounded-xl p-6">
          <h2 className="text-2xl font-bold mb-3">Formula</h2>
          <p className="font-mono bg-white border border-slate-200 rounded px-4 py-3">
            Payback (months) = CAC / (Monthly Revenue per Customer * Gross Margin)
          </p>
          <p className="text-slate-700 mt-3">
            Example: CAC $600, monthly revenue $100, gross margin 80% = 7.5 months payback.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">Practical Guardrails</h2>
          <ul className="list-disc pl-5 space-y-2 text-slate-700">
            <li>Less than 12 months is often considered healthy for many SaaS models.</li>
            <li>12 to 18 months can be workable with strong retention and cash reserves.</li>
            <li>Over 18 months usually requires tighter CAC controls or higher ARPU.</li>
          </ul>
        </section>

        <PaybackCalculatorClient />

        <section className="flex flex-wrap gap-3">
          <Link href="/cac-calculator" className="bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-blue-700 transition">Open CAC Calculator</Link>
          <Link href="/ltv-calculator" className="bg-slate-900 text-white px-4 py-2 rounded-lg font-semibold hover:bg-slate-800 transition">Open LTV Calculator</Link>
        </section>

        <section className="bg-slate-50 border border-slate-200 rounded-xl p-6">
          <h2 className="text-2xl font-bold mb-3">Related Calculators</h2>
          <div className="flex flex-wrap gap-3">
            <Link href="/mer-calculator" className="text-blue-700 hover:underline">MER Calculator</Link>
            <Link href="/roas/target-cpa" className="text-blue-700 hover:underline">Target CPA Calculator</Link>
            <Link href="/roas/break-even-roas" className="text-blue-700 hover:underline">Break-even ROAS</Link>
          </div>
        </section>
        <EmailCaptureCard source="payback_calculator" />

        <section className="text-sm text-slate-500 border-t border-slate-200 pt-6">
          Reviewed by ROAS Tools Editorial Team. Updated February 18, 2026.
        </section>
      </main>
    </div>
  );
}
