import { MetadataRoute } from 'next';
import { industryPages, platformPages, scenarioPages } from "@/app/lib/pseo";
import { BLOG_POSTS } from "@/app/lib/blog-posts";

// FULL SITEMAP - Include all static pages and all dynamic slug routes
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://roas-calculator.tech';
  const lastModified = new Date();
  const highPriorityRoutes = new Set([
    '/',
    '/ppc-toolkit',
    '/resources',
    '/resources/backlink-outreach-playbook',
    '/resources/seo-9of10-checklist',
    '/comparisons',
    '/comparisons/roas-vs-roi-vs-mer-vs-acos',
    '/comparisons/cac-vs-cpa-vs-roas',
    '/comparisons/mer-vs-roas',
    '/blog/roas-benchmarks-2026',
    '/learn/roas',
    '/benchmarks/roas',
    '/optimize/roas',
    '/profitability/ads',
    '/benchmarks/facebook-ads-roas',
    '/benchmarks/google-ads-roas',
    '/benchmarks/lead-gen-cpl-roas',
    '/blog/how-to-improve-roas-without-raising-budget',
    '/blog/roas-audit-checklist',
    '/blog/when-to-scale-or-pause-campaigns',
    '/blog/creative-testing-framework-for-roas',
    '/blog/payback-period-cash-flow-saas',
    '/blog/attribution-impact-on-roas',
    '/cac-calculator',
    '/ltv-calculator',
    '/mer-calculator',
    '/payback-period-calculator',
    '/break-even-roas-by-margin',
    '/resources/roas-planning-template',
    '/authors',
    '/methodology',
    '/data-sources',
    '/industry',
    '/platform',
    '/roas-scenarios',
    '/shopify-roas-calculator',
    '/amazon-roas',
    '/lead-generation-roas',
    '/saas-cac-payback',
  ]);

  const staticRoutes = [
    '/',
    '/blog',
    '/ppc-toolkit',
    '/cac-calculator',
    '/ltv-calculator',
    '/mer-calculator',
    '/payback-period-calculator',
    '/break-even-roas-by-margin',
    '/resources',
    '/resources/backlink-outreach-playbook',
    '/resources/seo-9of10-checklist',
    '/resources/ga4-conversion-mapping',
    '/resources/roas-planning-template',
    '/authors',
    '/methodology',
    '/data-sources',
    '/industry',
    '/platform',
    '/roas-scenarios',
    '/shopify-roas-calculator',
    '/amazon-roas',
    '/lead-generation-roas',
    '/saas-cac-payback',
    '/learn/roas',
    '/benchmarks/roas',
    '/benchmarks/facebook-ads-roas',
    '/benchmarks/google-ads-roas',
    '/benchmarks/lead-gen-cpl-roas',
    '/optimize/roas',
    '/profitability/ads',
    '/comparisons',
    '/comparisons/roas-vs-roi-vs-mer-vs-acos',
    '/comparisons/cac-vs-cpa-vs-roas',
    '/comparisons/mer-vs-roas',
    '/case-studies',
    '/testimonials',
    '/glossary',
    '/about',
    '/team',
    '/editorial-policy',
    '/contact',
    '/faq',
    '/terms',
    '/privacy-policy',
  ];
  const blogRoutes = BLOG_POSTS.map((post) => `/blog/${post.slug}`);
  const allStaticRoutes = [...new Set([...staticRoutes, ...blogRoutes])];

  const roasSlugs = [
    'facebook-ads',
    'tiktok-ads',
    'google-ads',
    'google-shopping-roas',
    'meta-dtc-roas',
    'lead-gen-cpl-roas',
    'dropshipping-profit',
    'break-even-roas',
    'marketing-roi',
    'amazon-ppc-acos',
    'influencer-roi',
    'target-cpa',
    'pinterest-ads',
  ];

  return [
    ...allStaticRoutes.map((route) => ({
      url: `${baseUrl}${route}`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: route === '/' ? 1 : highPriorityRoutes.has(route) ? 0.9 : 0.7,
    })),
    ...roasSlugs.map((slug) => ({
      url: `${baseUrl}/roas/${slug}`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
    ...industryPages.map((item) => ({
      url: `${baseUrl}/industry/${item.slug}/roas-calculator`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
    ...platformPages.map((item) => ({
      url: `${baseUrl}/platform/${item.slug}/roas-calculator`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
    ...scenarioPages.map((item) => ({
      url: `${baseUrl}/roas-scenarios/${item.slug}`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
  ];
}
